version: 2.1

var_1: &cache_key yarn-cache-{{ checksum "yarn.lock" }}
var_2: &run_in_node
  docker:
    - image: circleci/node:12.9.1
var_3: &run_in_browser
  docker:
    - image: circleci/node:12.9.1-browsers

jobs:
  install:
    <<: *run_in_node
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run: yarn --frozen-lockfile --non-interactive
      - save_cache:
          key: *cache_key
          paths:
            - ~/.cache/yarn
            - ~/.cache/Cypress
            - node_modules

  build:
    <<: *run_in_node
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run: yarn build

  test:
    <<: *run_in_node
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run: yarn test

  test-e2e:
    <<: *run_in_browser
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run: yarn affected:e2e --base=origin/master
            
workflows:
  version: 2
  build-test:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test-e2e:
          requires:
            - install
          filters:
            tags:
              only: /.*/
